repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-json # Optional: Fails fast on invalid JSON before formatting.
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        types: [json]
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.9
    hooks:
      - id: uv-lock
      - id: uv-export

