name: mobie_utils_2025
channels:
  - http://hof.cluster.embl.de/conda-forge
  - http://hof.cluster.embl.de/bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affogato=0.4.2
  - aiobotocore=2.23.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - aom=3.9.1
  - attrs=25.3.0
  - blosc=1.21.6
  - botocore=1.39.8
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.19.1
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.2
  - cluster_tools=0.5.0
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - docstring_parser=0.17.0
  - et_xmlfile=2.0.0
  - fftw=3.3.10
  - fonttools=4.59.0
  - freetype=2.13.3
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - giflib=5.2.2
  - glpk=5.0
  - gmp=6.3.0
  - h2=4.2.0
  - h5py=3.14.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2025.8.2
  - imageio=2.37.0
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - jmespath=1.0.1
  - joblib=1.5.1
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lemon=1.3.1
  - lerc=4.0.0
  - libaec=1.1.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.88.0
  - libboost-python=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libhwy=1.2.0
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvigra=1.12.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvmlite=0.44.0
  - lockfile=0.12.2
  - luigi=3.6.0
  - lz4-c=1.10.0
  - magicgui=0.10.1
  - matplotlib-base=3.10.5
  - mobie_utils=0.5.3
  - mrcfile=1.5.4
  - multidict=6.6.3
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.5
  - nifty=1.2.4
  - numba=0.61.2
  - numpy=2.2.6
  - openexr=3.3.5
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.1
  - packaging=25.0
  - pandas=2.3.1
  - pillow=11.3.0
  - pip=25.2
  - prometheus_client=0.14.1
  - propcache=0.3.1
  - psygnal=0.13.0
  - pthread-stubs=0.4
  - pybdv=0.5.4
  - pyconify=0.2.1
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.13.5
  - python-daemon=3.1.2
  - python-dateutil=2.9.0.post0
  - python-elf=0.7.3
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pywavelets=1.8.0
  - qhull=2020.2
  - qtpy=2.4.3
  - rav1e=0.7.1
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rpds-py=0.26.0
  - s3fs=2025.7.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - setuptools=80.9.0
  - six=1.17.0
  - skan=0.13.0
  - snappy=1.2.2
  - superqt=0.7.5
  - svt-av1=3.0.2
  - tenacity=8.5.0
  - threadpoolctl=3.6.0
  - tifffile=2025.6.11
  - tk=8.6.13
  - toml=0.10.2
  - toolz=1.0.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - urllib3=2.5.0
  - vigra=1.12.2
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yarl=1.20.1
  - z5py=2.0.20
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
